services:
  app_pg:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.pg
    environment:
      CONNECTION_URI: $APP_PG_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $APP_PG_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_PG_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_PG_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 4624:8080
